import type { BusinessProfile, PreCallIntel, PreCallSource } from "@/types/session";
import type { GapDiagnosis, NeighborhoodComparisonState, PainBriefExtras } from "@/types/scoutIntel";
import type { OpeningMode } from "@/types/presentationPack";
import { PreCallBriefPanel } from "@/components/field-read/PreCallBriefPanel";
import { cn } from "@/lib/utils/cn";

type ScoutBriefSectionProps = {
  intel: PreCallIntel;
  briefSource: PreCallSource | null;
  painExtras: PainBriefExtras | null;
  neighborhoodContext: NeighborhoodComparisonState;
  gapDiagnosis: GapDiagnosis | null;
  businessProfile: BusinessProfile | null;
  openingMode: OpeningMode;
  onContinue: () => void;
  onNewScout: () => void;
};

export function ScoutBriefSection({
  intel,
  briefSource,
  painExtras,
  neighborhoodContext,
  gapDiagnosis,
  businessProfile,
  openingMode,
  onContinue,
  onNewScout,
}: ScoutBriefSectionProps) {
  const name = businessProfile?.name?.trim() || "Business";
  const typeLine = businessProfile?.type?.trim() || "";

  return (
    <div className="mx-auto w-full max-w-xl space-y-4 sm:space-y-5">
      <div className="rounded-2xl border border-ink-border bg-ink-950 px-4 py-4 text-white shadow-[0_12px_40px_rgb(0_0_0/0.2)] sm:px-5 sm:py-5">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
          <div className="min-w-0">
            <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-teal-400/90">Brief</p>
            <h2 className="mt-1.5 text-xl font-bold tracking-tight sm:text-2xl">{name}</h2>
            {typeLine ? <p className="mt-1 text-sm text-white/55">{typeLine}</p> : null}
            <p className="mt-2 text-xs leading-snug text-white/45">
              Last look before the room — lines below match scout + intel; proof run uses the same diagnosis.
            </p>
          </div>
          <div className="flex shrink-0 flex-col items-stretch gap-2 sm:items-end">
            <div className="flex flex-wrap justify-end gap-2">
              {briefSource === "ai" ? (
                <span
                  className="rounded-lg border border-teal-500/40 bg-teal-950/50 px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-teal-100"
                  title="Generated by AI from scout inputs"
                >
                  AI brief
                </span>
              ) : briefSource === "deterministic" ? (
                <span
                  className="rounded-lg border border-white/15 bg-white/5 px-2 py-1 text-[10px] font-bold uppercase tracking-wide text-white/55"
                  title="Rules-based brief"
                >
                  Rules brief
                </span>
              ) : null}
            </div>
            <button
              type="button"
              onClick={onNewScout}
              className={cn(
                "min-h-10 rounded-xl border border-white/15 bg-white/5 px-4 text-xs font-semibold text-white/85 transition hover:border-white/25 hover:bg-white/10 sm:text-sm"
              )}
            >
              Rescan
            </button>
          </div>
        </div>
      </div>

      <PreCallBriefPanel
        intel={intel}
        painExtras={painExtras}
        neighborhoodContext={neighborhoodContext}
        gapDiagnosis={gapDiagnosis}
        businessProfile={businessProfile}
        openingMode={openingMode}
        onContinue={onContinue}
      />
    </div>
  );
}
