import type { PreCallIntel, PreCallSource } from "@/types/session";
import { PreCallBriefPanel } from "@/components/field-read/PreCallBriefPanel";

type ScoutBriefSectionProps = {
  intel: PreCallIntel;
  /** RFC 6A — AI vs rules-based brief (compact rep signal). */
  briefSource: PreCallSource | null;
  onContinue: () => void;
  onNewScout: () => void;
};

export function ScoutBriefSection({ intel, briefSource, onContinue, onNewScout }: ScoutBriefSectionProps) {
  return (
    <div className="space-y-6 sm:space-y-8">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div className="min-w-0">
          <div className="flex flex-wrap items-center gap-2">
            <h2 className="text-lg font-semibold tracking-tight text-foreground sm:text-xl">
              Brief locked in
            </h2>
            {briefSource === "ai" ? (
              <span
                className="rounded-full border border-signal-green/35 bg-signal-green/10 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-signal-green"
                title="Generated by AI from your scout inputs"
              >
                AI brief
              </span>
            ) : briefSource === "deterministic" ? (
              <span
                className="rounded-full border border-border bg-card px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-muted"
                title="Rules-based brief (AI unavailable or output invalid)"
              >
                Rules brief
              </span>
            ) : null}
          </div>
          <p className="mt-0.5 text-xs text-muted sm:text-sm">
            Walk-in lines below — then open live demo for proof.
          </p>
        </div>
        <button
          type="button"
          onClick={onNewScout}
          className="shrink-0 self-start rounded-lg border border-border bg-surface px-3 py-2 text-xs font-medium text-muted transition hover:border-accent/40 hover:text-foreground sm:self-center sm:px-4 sm:text-sm"
        >
          New scout
        </button>
      </div>
      <PreCallBriefPanel intel={intel} onContinue={onContinue} />
    </div>
  );
}
